<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Florive.DataAccess\Florive.DataAccess.csproj" />
    <ProjectReference Include="..\Florive.Domains\Florive.Domains.csproj" />
  </ItemGroup>

</Project>
